ztunnel:
  hub: ""
  tag: ""
  variant: ""

  # Can be a full hub/image:tag
  image: ztunnel

  resources:
    requests:
      cpu: 500m
      memory: 2048Mi

  env: {}
  podAnnotations:
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"

  # Additional labels to apply to the deployment.
  deploymentLabels: {}

  # Additional labels to apply on the pod level for monitoring and logging configuration.
  podLabels: {}

global:
  istioNamespace: istio-system
  # Default hub for Istio images.
  # Releases are published to docker hub under 'istio' project.
  # Dev builds from prow are on gcr.io
  hub: gcr.io/istio-testing
  # Default tag for Istio images.
  tag: latest
  # Variant of the image to use.
  # Currently supported are: [debug, distroless]
  variant: ""

  multiCluster:
    # Set to true to connect two kubernetes clusters via their respective
    # ingressgateway services when pods in each cluster cannot directly
    # talk to one another. All clusters should be using Istio mTLS and must
    # have a shared root CA for this model to work.
    enabled: false
    # Should be set to the name of the cluster this installation will run in. This is required for sidecar injection
    # to properly label proxies
    clusterName: ""

  # Specify image pull policy if default behavior isn't desired.
  # Default behavior: latest images will be Always else IfNotPresent.
  imagePullPolicy: ""

# Revision is set as 'version' label and part of the resource names when installing multiple control planes.
revision: ""

# meshConfig defines runtime configuration of components, including Istiod and istio-agent behavior
# For ztunnel, only defaultConfig is used.
# TODO: https://github.com/istio/istio/issues/43248
meshConfig:
  defaultConfig:
    proxyMetadata: {}

spireConfig:
  # Enable functionality to use spire with ambient mesh
  enable: false
  # Fixed socket path for spire
  socketPath: /run/secrets/workload-spiffe-uds